server_host: 0.0.0.0
server_port: 8888
server_transport: streamable-http
server_name: TaskMajor Server
taskrc: ~/.taskrc_mcp
taskdata: ~/.task_mcp
profiles_dir: "taskmajor/profiles"
profile: productivity
log_level: INFO
#log_level: DEBUG
log_format: text
agent_errors_path: /tmp/task/agent_errors.jsonl
otel_service_name: null
otel_enabled: true
otel_transport: grpc
otel_exporter_endpoint: null
otel_traces_endpoint: null
otel_metrics_endpoint: null
otel_logs_endpoint: null
